# Generated by Django 5.0.6 on 2024-07-26 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAndTime', models.DateTimeField(auto_now_add=True, verbose_name='Date And Time')),
                ('file', models.URLField(verbose_name='File Url')),
                ('result', models.CharField(max_length=150, verbose_name='Predicted Result')),
                ('confidence', models.CharField(max_length=50, verbose_name='Model Confidence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Prediction',
                'verbose_name_plural': 'Predictions',
            },
        ),
    ]
