# Generated by Django 5.0.6 on 2024-07-29 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird_voice_classifier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=50, verbose_name='Feedback Review')),
                ('desc', models.TextField(blank=True, verbose_name='Feedback Description')),
                ('correction', models.CharField(max_length=50, verbose_name='Correct Result')),
                ('predictiion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bird_voice_classifier.prediction', verbose_name='Feedback On')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
    ]
